name: nerf-pytorch
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - numpy
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - ipykernel
  - ipywidgets
  - matplotlib
  - scikit-learn
  - tqdm
  - tensorboard
  - imageio
  - "mkl<2024.1"
